[package]
name = "lumos-config-program"
description = "Lumos Config program"
documentation = "https://docs.rs/lumos-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }

[dev-dependencies]
lumos-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
