[package]
name = "lumos-ed25519-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

lumos-ed25519-dalek = { workspace = true }
lumos-rand = { workspace = true }

lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
