[package]
name = "lumos-local-cluster"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-rand = { workspace = true }

lumos-accounts-db = { workspace = true }
lumos-client = { workspace = true }
lumos-config-program = { workspace = true }
lumos-core = { workspace = true }
lumos-entry = { workspace = true }
lumos-gossip = { workspace = true }
lumos-ledger = { workspace = true }
lumos-logger = { workspace = true }
lumos-pubsub-client = { workspace = true }
lumos-quic-client = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-stake-program = { workspace = true }
lumos-streamer = { workspace = true }
lumos-thin-client = { workspace = true }
lumos-tpu-client = { workspace = true }
lumos-turbine = { workspace = true }
lumos-vote = { workspace = true }
lumos-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
lumos-download-utils = { workspace = true }
lumos-ledger = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
