[package]
name = "lumos-vote"
description = "Lumos vote"
documentation = "https://docs.rs/lumos-vote"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_derive = { workspace = true }
lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_vote"

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }

[features]
dev-context-only-utils = []
