[package]
name = "lpl-governance-addin-mock"
version = "0.1.4"
description = "Lumos Program Library Governance Voter Weight Addin Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
arrayref = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }

lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }
lpl-governance-addin-api = { workspace = true }
lpl-governance-tools = { workspace = true }
lpl-governance-test-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
