[package]
name = "lpl-governance-addin-mock"
version = "0.1.4"
description = "Lumos Program Library Governance Voter Weight Addin Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
bincode = "1.3.2"
borsh = "1.5.1"
num-derive = "0.4"
num-traits = "0.2"
serde = "1.0.204"
serde_derive = "1.0.103"
thiserror = "1.0"

lumos-program = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }
lpl-governance-addin-api = { workspace = true }
lpl-governance-tools = { workspace = true }
lpl-governance-test-sdk = { workspace = true }


[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.5"


[lib]
crate-type = ["cdylib", "lib"]
