[package]
name = "lumos-bpf-loader-program"
description = "Lumos BPF loader"
documentation = "https://docs.rs/lumos-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
scopeguard = { workspace = true }
thiserror = { workspace = true }

lumos-measure = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-zk-sdk = { workspace = true }
lumos-zk-token-sdk = { workspace = true }
rbpf = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
memoffset = { workspace = true }
rand = { workspace = true }
test-case = { workspace = true }

lumos-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
