[package]
name = "lpl-instruction-padding"
version = "0.2.0"
description = "Lumos Program Library Instruction Padding Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
homepage = "https://lumos.com/"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
num_enum = "0.7.2"
lumos-program = "2.0.0"

[dev-dependencies]
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
