[package]
name = "lumos-unified-scheduler-logic"
description = "The Lumos unified scheduler logic"
documentation = "https://docs.rs/lumos-unified-scheduler-logic"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lumos-sdk = { workspace = true }
