[package]
name = "lpl-token-metadata-example"
version = "0.3.0"
description = "Lumos Program Library Token Metadata Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
lumos-program = { workspace = true }
lpl-token-2022 = { version = "4.0.0", path = "../../token/program-2022", features = ["no-entrypoint"] }
lpl-token-metadata-interface = { version = "0.4.0", path = "../interface" }
lpl-type-length-value = { version = "0.5.0" , path = "../../libraries/type-length-value" }
lpl-pod = { version = "0.3.0", path = "../../libraries/pod" }

[dev-dependencies]
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token-client = { version = "0.11.0", path = "../../token/client" }
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
