[package]
name = "lpl-token-metadata-example"
version = "0.3.0"
description = "Lumos Program Library Token Metadata Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
test-case = { workspace = true }

lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

lpl-token-2022 = { workspace = true }
lpl-token-metadata-interface = { workspace = true }
lpl-type-length-value = { workspace = true }
lpl-pod = { workspace = true }
lpl-token-client = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
