[package]
name = "lumos-sbf-rust-upgradeable"
documentation = "https://docs.rs/lumos-sbf-rust-upgradeable"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lumos-program = { workspace = true }

[lib]
name = "lumos_sbf_rust_upgradeable"
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
