[package]
name = "lumos-secp256k1-recover"
description = "Lumos SECP256K1 Recover"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true, optional = true }
lumos-frozen-abi = { workspace = true, optional = true }
lumos-frozen-abi-macro = { workspace = true, optional = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "lumos")'.dependencies]
lumos-define-syscall = { workspace = true }

[target.'cfg(not(target_os = "lumos"))'.dependencies]
libsecp256k1 = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }

[target.'cfg(not(target_os = "lumos"))'.dev-dependencies]
libsecp256k1 = { workspace = true, features = ["hmac"] }

[build-dependencies]
rustc_version = { workspace = true, optional = true }

[features]
borsh = ["dep:borsh"]
frozen-abi = ["dep:rustc_version", "dep:lumos-frozen-abi", "dep:lumos-frozen-abi-macro"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
