[package]
name = "lumos-stake-program"
description = "Lumos Stake program"
documentation = "https://docs.rs/lumos-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
lumos-config-program = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
lumos-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
