[package]
name = "lumos-program"
description = "Lumos Program"
documentation = "https://docs.rs/lumos-program"
readme = "README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true } 

[dependencies]
bincode = { workspace = true }
blake3 = { workspace = true }
borsh = { workspace = true }
borsh0-10 = { workspace = true }
borsh0-9 = { workspace = true }
bs58 = { workspace = true }
bv = { workspace = true }
itertools =  { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
memoffset = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
rustversion = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }

rand = { workspace = true }
bytemuck = { workspace = true }
curve25519-dalek = { workspace = true }

lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-sdk-macro = { workspace = true }

anyhow = { workspace = true }
array-bytes = { workspace = true }
assert_matches = { workspace = true }
static_assertions = { workspace = true }


# This is currently needed to build on-chain programs reliably.
# Borsh 0.10 may pull in hashbrown 0.13, which uses ahash 0.8, which uses
# getrandom 0.2 underneath. This explicit dependency allows for no-std if cargo
# upgrades Borsh's dependency to hashbrown 0.13.
# Remove this once borsh 0.11 or 1.0 is released, which correctly declares the
# hashbrown dependency as optional.
[target.'cfg(target_os = "lumos")'.dependencies]
getrandom = { workspace = true }
[target.'cfg(not(target_os = "lumos"))'.dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
base64 = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
libsecp256k1 = { workspace = true }
light-poseidon = { workspace = true }
num-bigint = { workspace = true }
tiny-bip39 = { workspace = true }
wasm-bindgen = { workspace = true }
zeroize = { workspace = true }


[target.'cfg(not(target_os = "lumos"))'.dev-dependencies]
arbitrary = { workspace = true }
lumos-logger = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
getrandom = { workspace = true }
js-sys = { workspace = true }

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
parking_lot = { workspace = true }


[build-dependencies]
rustc_version = { workspace = true }

[target.'cfg(any(unix, windows))'.build-dependencies]
cc = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
