[package]
name = "lumos-sbf-rust-128bit"
documentation = "https://docs.rs/lumos-sbf-rust-128bit"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lumos-program = { workspace = true }
lumos-sbf-rust-128bit-dep = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
