[package]
name = "lumos-rpc"
description = "Lumos RPC"
documentation = "https://docs.rs/lumos-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
stream-cancel = { workspace = true }
thiserror = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-tokio = { workspace = true }
lumos-tokio-util = { workspace = true }

lumos-account-decoder = { workspace = true }
lumos-accounts-db = { workspace = true }
lumos-client = { workspace = true }
lumos-entry = { workspace = true }
lumos-faucet = { workspace = true }
lumos-gossip = { workspace = true }
lumos-ledger = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-perf = { workspace = true }
lumos-poh = { workspace = true }
lumos-rayon-threadlimit = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-send-transaction-service = { workspace = true }
lumos-stake-program = { workspace = true }
lumos-storage-bigtable = { workspace = true }
lumos-streamer = { workspace = true }
lumos-lvm = { workspace = true }
lumos-tpu-client = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-version = { workspace = true }
lumos-vote = { workspace = true }
lumos-vote-program = { workspace = true }
lpl-token = { workspace = true, features = ["no-entrypoint"] }
lpl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
serial_test = { workspace = true }
symlink = { workspace = true }

lumos-net-utils = { workspace = true }
lumos-runtime = { workspace = true, features = ["dev-context-only-utils"] }
lumos-stake-program = { workspace = true }
lpl-pod = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
