[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "lpl-token-client"
repository = "https://github.com/gaokanxu/lumos"
version = "0.11.0"

[dependencies]
async-trait = { workspace =  true }
curve25519-dalek = { workspace =  true }
futures = { workspace =  true }
futures-util = { workspace =  true }
thiserror = { workspace =  true }

lumos-banks-interface = { workspace =  true }
lumos-cli-output = { workspace =  true,  optional = true }
#lumos-program-test = { workspace = true }
lumos-rpc-client = { workspace =  true }
lumos-rpc-client-api = { workspace =  true }
lumos-sdk = { workspace = true }
lpl-associated-token-account = { workspace =  true }
lpl-memo = { workspace =  true }
lpl-token = { workspace =  true }
lpl-token-2022 = { workspace =  true }
lpl-token-group-interface = { workspace =  true }
lpl-token-metadata-interface = { workspace =  true }
lpl-transfer-hook-interface = { workspace =  true }


