[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "lpl-token-client"
repository = "https://github.com/gaokanxu/lumos"
version = "0.11.0"

[dependencies]
async-trait = "0.1"
curve25519-dalek = "3.2.1"
futures = "0.3.30"
futures-util = "0.3"
thiserror = "1.0"

lumos-banks-interface = { workspace =  true }
lumos-cli-output = { workspace =  true,  optional = true }
lumos-program-test = { workspace = true }
lumos-rpc-client = { workspace =  true }
lumos-rpc-client-api = { workspace =  true }
lumos-sdk = { workspace = true }
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
lpl-associated-token-account = { workspace =  true }
lpl-memo = { workspace =  true }
lpl-token = { workspace =  true }
lpl-token-2022 = { workspace =  true }
lpl-token-group-interface = { workspace =  true }
lpl-token-metadata-interface = { workspace =  true }
lpl-transfer-hook-interface = { workspace =  true }


[features]
default = ["display"]
display = ["lumos-cli-output"]

