[package]
name = "lpl-token"
version = "6.0.0"
description = "Lumos Program Library Token"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
bytemuck = "1.16.1"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
lumos-program = "2.0.0"
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.5.0"
proptest = "1.5"
serial_test = "3.1.1"
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
