[package]
name = "lpl-token"
version = "6.0.0"
description = "Lumos Program Library Token"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[dependencies]
arrayref = { workspace = true }
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
proptest = { workspace = true }
serial_test = { workspace = true }


lumos-program = { workspace = true }
#lumos-program-test = { workspace = true } 
lumos-sdk = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
