[package]
name = "lpl-name-service"
description = "Lumos Program Library Name Service"
version = "0.3.0"
repository = "https://github.com/gaokanxu/lumos-program-library"
authors = [
  "lcchy <lucas@bonfida.com>",
  "Gao Kanxu <gaokanxu@gmail.com>",
]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
lumos-program = "2.0.0"
num-traits = "0.2"
borsh = "1.5.1"
num-derive = "0.4.2"
thiserror = "1.0.63"

[dev-dependencies]
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]
