[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL Token Lending CLI"
edition = "2021"
homepage = "https://spl.lumos.com/token-lending"
license = "Apache-2.0"
name = "lpl-token-lending-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "0.2.0"

[dependencies]
clap = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-sdk = { workspace = true }
lumos-program = { workspace = true }
lpl-token-lending = { workspace = true }
lpl-token = { workspace = true }

[[bin]]
name = "lpl-token-lending"
path = "src/main.rs"
