[package]
name = "lumos-cargo-build-sbf"
description = "Compile a local package and all of its dependencies using the Lumos SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bzip2 = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
lumos-download-utils = { workspace = true }
lumos-logger = { workspace = true }
lumos-sdk = { workspace = true }
tar = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
serial_test = { workspace = true }
lumos-sdk = { workspace = true }

[features]
program = []

[[bin]]
name = "cargo-build-sbf"
path = "src/main.rs"
