[package]
name = "lumos-geyser-plugin-manager"
description = "The Lumos Geyser plugin manager."
documentation = "https://docs.rs/lumos-geyser-plugin-manager"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
json5 = { workspace = true }
jsonrpc-core = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

crossbeam-channel = { workspace = true }

lumos-accounts-db = { workspace = true }
lumos-entry = { workspace = true }
lumos-geyser-plugin-interface = { workspace = true }
lumos-ledger = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-rpc = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-transaction-status = { workspace = true }
tokio = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
