[package]
name = "lpl-pod"
version = "0.3.0"
description = "Lumos Program Library Plain Old Data (Pod)"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }

bytemuck = { workspace = true }
bytemuck-derive = { workspace = true }

lumos-program = { workspace = true }
lumos-zk-token-sdk = { workspace = true }
lpl-program-error = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
