[package]
name = "lumos-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

lumos-rand = { workspace = true }

lumos-clap-utils = { workspace = true }
lumos-cli = { workspace = true }
lumos-client = { workspace = true }
lumos-core = { workspace = true }
lumos-faucet = { workspace = true }
lumos-gossip = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-version = { workspace = true }

[dev-dependencies]
lumos-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
