[package]
name = "lumos-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-validator"
default-run = "lumos-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }

crossbeam-channel = { workspace = true }
rand = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-accounts-db = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-core = { workspace = true }
lumos-download-utils = { workspace = true }
lumos-entry = { workspace = true }
lumos-faucet = { workspace = true }
lumos-genesis-utils = { workspace = true }
lumos-geyser-plugin-interface = { workspace = true }
lumos-geyser-plugin-manager = { workspace = true }
lumos-gossip = { workspace = true }
lumos-ledger = { workspace = true }
lumos-logger = { workspace = true }
lumos-metrics = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-perf = { workspace = true }
lumos-poh = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-rayon-threadlimit = { workspace = true }
lumos-rpc = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-send-transaction-service = { workspace = true }
lumos-storage-bigtable = { workspace = true }
lumos-streamer = { workspace = true }
lumos-test-validator = { workspace = true }
lumos-tpu-client = { workspace = true }
lumos-unified-scheduler-pool = { workspace = true }
lumos-version = { workspace = true }
lumos-vote-program = { workspace = true }
tokio = { workspace = true }
lpl-token-2022 = { workspace = true }



[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
