[package]
name = "lpl-token-wrap"
version = "0.1.0"
description = "Lumos Program Library Token Wrap"
authors = ["Lumos Maintainers <maintainers@lumos.foundation>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
num_enum = "0.7"
lumos-program = "2.0.0"
lpl-associated-token-account = { version = "4.0.0", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
lpl-token = { version = "6.0", path = "../../token/program", features = ["no-entrypoint"] }
lpl-token-2022 = { version = "4.0.0", path = "../../token/program-2022", features = ["no-entrypoint"] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
