[package]
name = "lpl-token-wrap"
version = "0.1.0"
description = "Lumos Program Library Token Wrap"
authors = ["Lumos Maintainers <maintainers@lumos.foundation>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytemuck = { workspace = true }
num_enum = { workspace = true }
lumos-program = { workspace = true }
lpl-associated-token-account = { workspace = true }
lpl-token = { workspace = true }
lpl-token-2022 = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
