[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL Transfer Hook Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/token"
license = "Apache-2.0"
name = "lpl-transfer-hook-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "0.2.0"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.30"
strum = "0.26"
strum_macros = "0.26"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"

lumos-clap-v3-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-sdk = { workspace = true }
lpl-tlv-account-resolution = { workspace = true, features = ["serde-traits"] }
lpl-transfer-hook-interface = { workspace = true }

[dev-dependencies]
lumos-test-validator = { workspace = true }
lpl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
lpl-token-client = { workspace = true }
lpl-transfer-hook-example = { workspace = true }

[[bin]]
name = "lpl-transfer-hook"
path = "src/main.rs"
