[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL Transfer Hook Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/token"
license = "Apache-2.0"
name = "lpl-transfer-hook-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "0.2.0"

[dependencies]
clap = { workspace = true }
futures-util = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }

lumos-tokio = { workspace = true }

lumos-clap-v3-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-sdk = { workspace = true }
lpl-tlv-account-resolution = { workspace = true }
lpl-transfer-hook-interface = { workspace = true }

[dev-dependencies]
lumos-test-validator = { workspace = true }
lpl-token-2022 = { workspace = true }
lpl-token-client = { workspace = true }
lpl-transfer-hook-example = { workspace = true }

[[bin]]
name = "lpl-transfer-hook"
path = "src/main.rs"
