[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL Transfer Hook Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/token"
license = "Apache-2.0"
name = "lpl-transfer-hook-cli"
repository = "https://github.com/gaokanxu/lumos-program-library"
version = "0.2.0"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.30"
lumos-clap-v3-utils = "2.0.0"
lumos-cli-config = "2.0.0"
lumos-client = "2.0.0"
lumos-logger = "2.0.0"
lumos-remote-wallet = "2.0.0"
lumos-sdk = "2.0.0"
lpl-tlv-account-resolution = { version = "0.7.0" , path = "../../../libraries/tlv-account-resolution", features = ["serde-traits"] }
lpl-transfer-hook-interface = { version = "0.7.0", path = "../interface" }
strum = "0.26"
strum_macros = "0.26"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"

[dev-dependencies]
lumos-test-validator = "2.0.0"
lpl-token-2022 = { version = "4.0.0", path = "../../program-2022", features = ["no-entrypoint"] }
lpl-token-client = { version = "0.11.0", path = "../../client" }
lpl-transfer-hook-example = { version = "0.6.0", path = "../example" }

[[bin]]
name = "lpl-transfer-hook"
path = "src/main.rs"
