[package]
name = "lumos-merkle-tree"
description = "Lumos Merkle Tree"
documentation = "https://docs.rs/lumos-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
fast-math = { workspace = true }
hex = { workspace = true }

lumos-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
