[package]
name = "lpl-binary-oracle-pair"
version = "0.1.0"
description = "Lumos Program Library Binary Oracle Pair"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
lumos-program = "2.0.0"
lpl-token = { version = "6.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
thiserror = "1.0"
uint = "0.9"
borsh = "1.5.1"

[dev-dependencies]
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]
