[package]
name = "lpl-binary-oracle-pair"
version = "0.1.0"
description = "Lumos Program Library Binary Oracle Pair"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
thiserror = "1.0"
uint = "0.9"
borsh = "1.5.1"

lumos-program = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]
