[package]
name = "lpl-binary-oracle-pair"
version = "0.1.0"
description = "Lumos Program Library Binary Oracle Pair"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
uint = { workspace = true }
borsh = { workspace = true }

lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]
