[package]
name = "stateless-asks"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { workspace = true }
lumos-program = { workspace = true }
lpl-token = { workspace = true }
lpl-associated-token-account = { workspace = true }
thiserror = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
