[package]
name = "lumos-gossip"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-gossip"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
num-traits = { workspace = true }
rayon = { workspace = true }
rustversion = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-rand = { workspace = true }
lumos-rand-chacha = { workspace = true }

lumos-bloom = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-client = { workspace = true }
lumos-connection-cache = { workspace = true }
lumos-entry = { workspace = true }
lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-ledger = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-perf = { workspace = true }
lumos-rayon-threadlimit = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
lumos-tpu-client = { workspace = true }
lumos-version = { workspace = true }
lumos-vote = { workspace = true }
lumos-vote-program = { workspace = true }


[dev-dependencies]
num_cpus = { workspace = true }
serial_test = { workspace = true }
lumos-runtime = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "lumos-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
