[package]
name = "lumos-transaction-status"
description = "Lumos transaction status types"
documentation = "https://docs.rs/lumos-transaction-status"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
Inflector = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
# Update this borsh dependency to the workspace version once
# lpl-associated-token-account is upgraded and used in the monorepo.
borsh =  { workspace = true }
bs58 = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-sdk = { workspace = true }
lpl-associated-token-account = { workspace = true }
lpl-memo = { workspace = true }
lpl-token = { workspace = true }
lpl-token-2022 = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
