# This package only exists to avoid circular dependencies during cargo publish:
# lumos-bpf-loader-program -> lumos-program-test -> lumos-bpf-loader-program

[package]
name = "lumos-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
lumos-bpf-loader-program = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
