[package]
name = "lpl-shared-memory"
version = "2.0.6"
description = "Lumos Program Library Shared-memory"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
arrayref = "0.3.8"
lumos-program = { workspace = true }

[dev-dependencies]
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
