[package]
name = "binary-option"
version = "0.1.0"
edition = "2021"
license = "WTFPL"

[dependencies]
thiserror = { workspace = true }
arrayref = { workspace = true }
borsh = { workspace = true }
uint = { workspace = true }

lumos-program = { workspace = true }
lpl-token = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]
