[package]
name = "test-client"
version = "0.1.0"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
publish = false
edition = "2021"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
lumos-sdk = { workspace = true }
lpl-memo = { workspace = true }
lpl-token = { workspace = true }
lpl-token-swap = { workspace = true }
