[package]
name = "lpl-transfer-hook-example"
version = "0.6.0"
description = "Lumos Program Library Transfer Hook Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["forbid-additional-mints"]
no-entrypoint = []
test-sbf = []
forbid-additional-mints = []

[dependencies]
arrayref = { workspace = true }

lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

lpl-tlv-account-resolution = { workspace = true }
lpl-token-2022 = { workspace = true }
lpl-transfer-hook-interface = { workspace = true }
lpl-type-length-value = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
