[package]
name = "lpl-transfer-hook-example"
version = "0.6.0"
description = "Lumos Program Library Transfer Hook Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["forbid-additional-mints"]
no-entrypoint = []
test-sbf = []
forbid-additional-mints = []

[dependencies]
arrayref = "0.3.8"
lumos-program = { workspace = true }
lpl-tlv-account-resolution = { version = "0.7.0" , path = "../../../libraries/tlv-account-resolution" }
lpl-token-2022 = { version = "4.0.0",  path = "../../program-2022", features = ["no-entrypoint"] }
lpl-transfer-hook-interface = { version = "0.7.0" , path = "../interface" }
lpl-type-length-value = { version = "0.5.0" , path = "../../../libraries/type-length-value" }

[dev-dependencies]
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
