[package]
name = "lumos-program-runtime"
description = "Lumos program runtime"
documentation = "https://docs.rs/lumos-program-runtime"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
eager = { workspace = true }
enum-iterator = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
percentage = { workspace = true }
serde = { workspace = true }
assert_matches = { workspace = true }
libsecp256k1 = { workspace = true }
test-case = { workspace = true }

lumos-rand = { workspace = true }

lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-sdk = { workspace = true }
lumos-rbpf = { workspace = true }
thiserror = { workspace = true }
lumos-logger = { workspace = true }



[lib]
crate-type = ["lib"]
name = "lumos_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
