[package]
name = "lpl-token-confidential-transfer-proof-generation"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Proof Generation"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
curve25519-dalek = "3.2.1"
lumos-zk-sdk = "2.0.0"
thiserror = "1.0.63"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
