[package]
name = "lumos-udp-client"
description = "Lumos UDP Client"
documentation = "https://docs.rs/lumos-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
lumos-connection-cache = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
