[package]
name = "lpl-single-pool"
version = "1.0.1"
description = "Lumos Program Library Single-Validator Stake Pool"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = { workspace =  true }
borsh = { workspace =  true }
num-derive = { workspace =  true }
num-traits = { workspace =  true }
num_enum = { workspace =  true }
thiserror = { workspace =  true }
test-case = { workspace =  true }
bincode = { workspace =  true }
rand = { workspace =  true }
approx = { workspace =  true }

security-txt = { workspace =  true }

lumos-program = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }
#lumos-program-test = { workspace = true }

lpl-token = { workspace = true }
lpl-associated-token-account = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

