[package]
name = "lumos-unified-scheduler-pool"
description = "The Lumos unified scheduler pool"
documentation = "https://docs.rs/lumos-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }

crossbeam-channel = { workspace = true }

lumos-logger = { workspace = true }
lumos-ledger = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-unified-scheduler-logic = { workspace = true }
lumos-vote = { workspace = true }

