[package]
name = "lumos-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }

lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-sdk = { workspace = true }
lumos-stake-program = { workspace = true }
lumos-version = { workspace = true }
lumos-runtime = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
