[package]
name = "lumos-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-cli-output = { workspace = true }
lumos-logger = { workspace = true }
lumos-metrics = { workspace = true }
lumos-notifier = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-sdk = { workspace = true }
lumos-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
