[package]
name = "lumos-zk-token-proof-program"
description = "Lumos Zk Token Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }

lumos-bytemuck = { workspace = true }

lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-zk-token-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
lumos-curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
