[package]
name = "lpl-token-upgrade"
version = "0.1.1"
description = "Lumos Program Library Token Upgrade"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
thiserror = { workspace = true }
test-case = { workspace = true }

#lumos-program-test = { workspace = true }
lumos-program = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }
lpl-token-client = { workspace = true }
lpl-token-2022 = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
