[package]
name = "lpl-token-upgrade"
version = "0.1.1"
description = "Lumos Program Library Token Upgrade"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
thiserror = "1.0"

lumos-program = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true, features = ["no-entrypoint"] }
lpl-token-client = { workspace = true }
lpl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
lumos-program-test = { workspace = true }
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
