[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/stake-pool"
license = "Apache-2.0"
name = "lpl-stake-pool-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "2.0.0"

[dependencies]
borsh = "1.5.1"
clap = "2.33.3"
serde = "1.0.204"
serde_derive = "1.0.130"
serde_json = "1.0.120"
bs58 = "0.5.1"
bincode = "1.3.1"


lumos-account-decoder = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-cli-output = { workspace = true }
lumos-client = { workspace = true }
lumos-logger = { workspace = true }
lumos-program = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-sdk = { workspace = true }
lpl-associated-token-account = { workspace = true }
lpl-stake-pool = { workspace = true }
lpl-token = { workspace = true }

[[bin]]
name = "lpl-stake-pool"
path = "src/main.rs"
