[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/stake-pool"
license = "Apache-2.0"
name = "lpl-stake-pool-cli"
repository = "https://github.com/gaokanxu/lumos-program-library"
version = "2.0.0"

[dependencies]
borsh = "1.5.1"
clap = "2.33.3"
serde = "1.0.204"
serde_derive = "1.0.130"
serde_json = "1.0.120"
lumos-account-decoder = "2.0.0"
lumos-clap-utils = "2.0.0"
lumos-cli-config = "2.0.0"
lumos-cli-output = "2.0.0"
lumos-client = "2.0.0"
lumos-logger = "2.0.0"
lumos-program = "2.0.0"
lumos-remote-wallet = "2.0.0"
lumos-sdk = "2.0.0"
lpl-associated-token-account = { version = "=4.0.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
lpl-stake-pool = { version = "=2.0.0", path = "../program", features = [
  "no-entrypoint",
] }
lpl-token = { version = "=6.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
bs58 = "0.5.1"
bincode = "1.3.1"

[[bin]]
name = "lpl-stake-pool"
path = "src/main.rs"
