[package]
name = "lumos-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true }
serde = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-clap-utils = { workspace = true }
lumos-cli-config = { workspace = true }
lumos-remote-wallet = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-sdk = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-version = { workspace = true }
lpl-associated-token-account = { workspace = true }
lpl-token = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
lumos-logger = { workspace = true }
lumos-streamer = { workspace = true }
lumos-test-validator = { workspace = true }
