[package]
name = "lumos-quic-client"
description = "Lumos Quic Client"
documentation = "https://docs.rs/lumos-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
thiserror = { workspace = true }

lumos-connection-cache = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
lumos-tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
lumos-crossbeam-channel = { workspace = true }
lumos-logger = { workspace = true }
lumos-perf = { workspace = true }
