[package]
name = "lumos-perf"
description = "Lumos Performance APIs"
documentation = "https://docs.rs/lumos-perf"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
ahash = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
dlopen2 = { workspace = true }
fnv = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

curve25519-dalek = { workspace = true }
rand = { workspace = true }

lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-metrics = { workspace = true }
lumos-rayon-threadlimit = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }

[target."cfg(target_os = \"linux\")".dependencies]
caps = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }

[lib]
name = "lumos_perf"

[dev-dependencies]
assert_matches = { workspace = true }
rand-chacha = { workspace = true }
lumos-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[[bench]]
name = "sigverify"

[[bench]]
name = "discard"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
