[package]
name = "lpl-governance-addin-api"
version = "0.1.4"
description = "Lumos Program Library Governance Addin Api"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
lpl-governance-tools = { version = "0.1.4", path = "../tools" }
lumos-program = "2.0.0"
