[package]
name = "lumos-zk-token-sdk"
description = "Lumos Zk Token SDK"
documentation = "https://docs.rs/lumos-zk-token-sdk"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }

lumos-bytemuck = { workspace = true, features = ["derive"] }
lumos-program = { workspace = true }

[dev-dependencies]
tiny-bip39 = { workspace = true }

[target.'cfg(not(target_os = "lumos"))'.dependencies]
sha3 = { workspace = true }
aes-gcm-siv = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
getrandom = { version = "0.1", features = ["dummy"] }
itertools = { workspace = true }
lazy_static = { workspace = true }
merlin = { workspace = true }
rand = { version = "0.7" }
serde = { workspace = true }
serde_json = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }

lumos-curve25519-dalek = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

