[package]
name = "lumos-zk-token-sdk"
description = "Lumos Zk Token SDK"

version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }

bytemuck = { workspace = true, features = ["derive"] }
bytemuck-derive = { workspace = true } 
lumos-program = { workspace = true }
lumos-curve25519 = { workspace = true }

tiny-bip39 = { workspace = true }

sha3 = { workspace = true }
aes-gcm-siv = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
getrandom = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
merlin = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }

curve25519-dalek = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

