[package]
name = "lumos-poh-bench"
documentation = "https://docs.rs/lumos-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
lumos-entry = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-perf = { workspace = true }
lumos-sdk = { workspace = true }
lumos-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
