[package]
name = "lpl-governance-tools"
version = "0.1.4"
description = "Lumos Program Library Governance Tools"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
lumos-program = { workspace = true }
lpl-token = { workspace = true }
thiserror = { workspace = true }
