[package]
name = "lpl-token-swap"
version = "3.0.0"
description = "Lumos Program Library Token Swap"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = { workspace = true }
enum_dispatch = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
arbitrary = { workspace = true }
roots = { workspace = true }
proptest = { workspace = true }
test-case = { workspace = true }

lumos-program = { workspace = true }
lumos-sdk = { workspace = true }

lpl-math = { workspace = true }
lpl-token = { workspace = true }
lpl-token-2022 = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
