[package]
name = "lpl-token-swap"
version = "3.0.0"
description = "Lumos Program Library Token Swap"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
production = []
fuzz = ["arbitrary", "roots"]

[dependencies]
arrayref = "0.3.8"
enum_dispatch = "0.3.13"
num-derive = "0.4"
num-traits = "0.2"
lumos-program = "2.0.0"
lpl-math = { version = "0.2", path = "../../libraries/math", features = [ "no-entrypoint" ] }
lpl-token = { version = "6.0", path = "../../token/program", features = [ "no-entrypoint" ] }
lpl-token-2022 = { version = "4.0.0", path = "../../token/program-2022", features = [ "no-entrypoint" ] }
thiserror = "1.0"
arbitrary = { version = "1.3", features = ["derive"], optional = true }
roots = { version = "0.0.8", optional = true }

[dev-dependencies]
proptest = "1.5"
roots = "0.0.8"
lumos-sdk = "2.0.0"
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
