[package]
name = "lpl-example-sysvar"
version = "1.0.0"
description = "Lumos Program Library Sysvar Example"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
lumos-program = "2.0.0"

[dev-dependencies]
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
