[package]
name = "lumos-turbine"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos-turbine"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
quinn = { workspace = true }
rayon = { workspace = true }
rustls = { workspace = true }
thiserror = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-rand = { workspace = true }
lumos-rand-chacha = { workspace = true }

lumos-entry = { workspace = true }
lumos-gossip = { workspace = true }
lumos-ledger = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-perf = { workspace = true }
lumos-poh = { workspace = true }
lumos-quic-client = { workspace = true }
lumos-rayon-threadlimit = { workspace = true }
lumos-rpc = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
lumos-tokio = { workspace = true }


[dev-dependencies]
assert_matches = { workspace = true }
test-case = { workspace = true }

lumos-logger = { workspace = true }
lumos-runtime = { workspace = true }

[[bench]]
name = "cluster_info"

[[bench]]
name = "cluster_nodes"

[[bench]]
name = "retransmit_stage"
