[package]
name = "lpl-token-swap-fuzz"
version = "0.0.1"
description = "Lumos Program Library Token Swap Fuzzer"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = { version = "0.5.56" }
arbitrary = { version = "1.3", features = ["derive"] }
lumos-program = "2.0.0"
lpl-math = { version = "0.2", path = "../../../libraries/math", features = [ "no-entrypoint" ] }
lpl-token = { version = "6.0", path = "../../../token/program", features = [ "no-entrypoint" ] }
lpl-token-swap = { path = "..", features = ["fuzz", "no-entrypoint"] }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false
