[package]
name = "lpl-token-swap-fuzz"
version = "0.0.1"
description = "Lumos Program Library Token Swap Fuzzer"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = { workspace = true }
arbitrary = { workspace = true }

lumos-program = { workspace = true }
lpl-math = { workspace = true }
lpl-token = { workspace = true }
lpl-token-swap = { workspace = true }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false
