[package]
name = "lumos-geyser-plugin-interface"
description = "The Lumos Geyser plugin interface."
documentation = "https://docs.rs/lumos-geyser-plugin-interface"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
lumos-sdk = { workspace = true }
lumos-transaction-status = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
