[package]
name = "lumos-runtime-transaction"
description = "Lumos runtime-transaction"
documentation = "https://docs.rs/lumos-runtime-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }

rand = { workspace = true }

lumos-program ={ workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_runtime_transaction"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }
