[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "lpl-token-2022-test"
repository = "https://github.com/gaokanxu/lumos"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
futures-util = { workspace = true }
test-case = { workspace = true }

lumos-program = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-associated-token-account = { workspace = true }
lpl-memo = { workspace = true }
lpl-pod = { workspace = true }
lpl-token-2022 = { workspace = true }
lpl-instruction-padding = { workspace = true }
lpl-tlv-account-resolution = { workspace = true }
lpl-token-client = { workspace = true }
lpl-token-group-interface = { workspace = true }
lpl-token-metadata-interface = { workspace = true }
lpl-transfer-hook-example = { workspace = true }
lpl-transfer-hook-interface = { workspace = true }

