[package]
name = "lpl-discriminator"
version = "0.3.0"
description = "Lumos Program Library 8-Byte Discriminator Management"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "1", optional = true }
bytemuck = { version = "1.16.1", features = ["derive"] }
lumos-program = { workspace = true }
lpl-discriminator-derive = { version = "0.2.0", path = "./derive" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
