[package]
name = "lpl-token-confidential-transfer-proof-extraction"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Proof Extraction"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.1"
lumos-curve25519 = "2.0.0"
lumos-zk-sdk = "2.0.0"
thiserror = "1.0.63"

[lib]
crate-type = ["cdylib", "lib"]
