[package]
name = "lpl-token-confidential-transfer-proof-extraction"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Proof Extraction"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
thiserror = { workspace = true }
lumos-curve25519-dalek = { workspace = true }
lumos-zk-sdk = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]
