[package]
name = "lpl-token-metadata-interface"
version = "0.4.0"
description = "Lumos Program Library Token Metadata Interface"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

lumos-program = { workspace = true }

lpl-discriminator = { workspace = true }
lpl-program-error = { workspace = true }
lpl-type-length-value = { workspace = true }
lpl-pod = { workspace = true }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
