[package]
name = "lumos-zk-token-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
lumos-bytemuck = { workspace = true }

lumos-curve25519-dalek = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lumos-zk-token-sdk = { workspace = true }

