# This package only exists to avoid circular dependencies during cargo publish:
# lumos-runtime -> lumos-address-program -> lumos-program-test -> lumos-runtime

[package]
name = "lumos-address-lookup-table-program-tests"
publish = false

version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
lumos-address-lookup-table-program = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
