[package]
name = "lumos-pubsub-client"
description = "Lumos Pubsub Client"
documentation = "https://docs.rs/lumos-pubsub-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
url = { workspace = true }

crossbeam-channel = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }

lumos-account-decoder = { workspace = true }
lumos-rpc-client-api = { workspace = true }
lumos-sdk = { workspace = true }



[dev-dependencies]
anyhow = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
