[package]
name = "lumos-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

lumos-crossbeam-channel = { workspace = true }

lumos-accounts-db = { workspace = true }
lumos-cli-output = { workspace =  true,  optional = true }
lumos-client = { workspace = true }
lumos-core = { workspace = true }
lumos-geyser-plugin-manager = { workspace = true }
lumos-gossip = { workspace = true }
lumos-ledger = { workspace = true }
lumos-logger = { workspace = true }
lumos-net-utils = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-program-test = { workspace = true }
lumos-rpc = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-streamer = { workspace = true }
lumos-tpu-client = { workspace = true }
lumos-tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
