[package]
name = "lumos-net-utils"
description = "Lumos Network Utilities"
documentation = "https://docs.rs/lumos-net-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace=true, features = ["cargo"] }
log = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
socket2 = { workspace = true }
url = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-rand = { workspace = true }

lumos-logger = { workspace = true }
lumos-sdk = { workspace = true }
lumos-version = { workspace = true }
lumos-tokio = { workspace = true }


[lib]
name = "lumos_net_utils"

[[bin]]
name = "lumos-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "lumos-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
