[package]
name = "lpl-stake-pool"
version = "2.0.0"
description = "Lumos Program Library Stake Pool"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.8"
borsh = "1.5.1"
bytemuck = "1.16"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
serde = "1.0.204"
serde_derive = "1.0.103"

security-txt = { workspace = true }
lumos-program = { workspace = true }
#lpl-math = { workspace = true }
lpl-pod = { workspace = true }
lpl-token-2022 = { workspace = true }
lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }
lpl-token = { workspace = true }


thiserror = "1.0"
bincode = "1.3.1"

[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.5"
test-case = "3.3"

[lib]
crate-type = ["cdylib", "lib"]
