[package]
name = "lpl-stake-pool"
version = "2.0.0"
description = "Lumos Program Library Stake Pool"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = { workspace = true }
borsh = { workspace = true }
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }
assert_matches = { workspace = true }
proptest = { workspace = true }
test-case = { workspace = true }

security-txt = { workspace = true }
lumos-program = { workspace = true }
#lpl-math = { workspace = true }
lpl-pod = { workspace = true }
lpl-token-2022 = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lumos-vote-program = { workspace = true }
lpl-token = { workspace = true }



[lib]
crate-type = ["cdylib", "lib"]
