[package]
name = "lpl-concurrent-merkle-tree"
version = "0.3.0"
description = "Lumos Program Library Concurrent Merkle Tree"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
log = []
sol-log = ["log"]

[dependencies]
lumos-program = ">=1.18.11,<=2"
bytemuck = "1.16"
thiserror = "1.0.63"

[dev-dependencies]
rand_distr = "0.4.3"
rand = "0.8"
lpl-merkle-tree-reference = { version = "0.1.0", path = "../merkle-tree-reference" }
tokio = { version = "1.39", features = ["full"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
