[package]
name = "lpl-concurrent-merkle-tree"
version = "0.3.0"
description = "Lumos Program Library Concurrent Merkle Tree"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"


[dependencies]
thiserror = { workspace =  true }

lumos-bytemuck = { workspace =  true }
lumos-rand-distr = { workspace =  true }
lumos-rand = { workspace =  true }
lumos-tokio = { workspace =  true }

lumos-program = { workspace =  true }
lpl-merkle-tree-reference = { workspace =  true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
