[workspace.package]
version = "2.0.0"
description = "Lumos SBF test program written in Rust"
authors = ["Lumos Labs Maintainers <maintainers@lumoslabs.com>"]
repository = "https://github.com/lumos-labs/lumos"
homepage = "https://lumoslabs.com/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
array-bytes = "=1.4.1"
bincode = { version = "1.1.4", default-features = false }
blake3 = "1.0.0"
byteorder = "1.3.2"
elf = "0.0.10"
getrandom = "0.2.10"
itertools = "0.10.1"
libsecp256k1 = { version = "0.7.0", default-features = false }
log = "0.4.11"
miow = "0.3.6"
net2 = "0.2.37"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
rustversion = "1.0.14"
serde = "1.0.112"
serde_json = "1.0.56"
lumos-account-decoder = { path = "../../account-decoder", version = "=2.0.0" }
lumos-accounts-db = { path = "../../accounts-db", version = "=2.0.0" }
lumos-bpf-loader-program = { path = "../bpf_loader", version = "=2.0.0" }
lumos-cli-output = { path = "../../cli-output", version = "=2.0.0" }
lumos-ledger = { path = "../../ledger", version = "=2.0.0" }
lumos-logger = { path = "../../logger", version = "=2.0.0" }
lumos-measure = { path = "../../measure", version = "=2.0.0" }
lumos-program = { path = "../../sdk/program", version = "=2.0.0" }
lumos-program-runtime = { path = "../../program-runtime", version = "=2.0.0" }
lumos-program-test = { path = "../../program-test", version = "=2.0.0" }
lumos-runtime = { path = "../../runtime", version = "=2.0.0" }
lumos-sbf-rust-128bit-dep = { path = "rust/128bit_dep", version = "=2.0.0" }
lumos-sbf-rust-invoke = { path = "rust/invoke", version = "=2.0.0" }
lumos-sbf-rust-invoked = { path = "rust/invoked", version = "=2.0.0", default-features = false }
lumos-sbf-rust-many-args-dep = { path = "rust/many_args_dep", version = "=2.0.0" }
lumos-sbf-rust-mem = { path = "rust/mem", version = "=2.0.0" }
lumos-sbf-rust-param-passing-dep = { path = "rust/param_passing_dep", version = "=2.0.0" }
lumos-sbf-rust-realloc = { path = "rust/realloc", version = "=2.0.0", default-features = false }
lumos-sbf-rust-realloc-invoke = { path = "rust/realloc_invoke", version = "=2.0.0" }
lumos-sdk = { path = "../../sdk", version = "=2.0.0" }
lumos-svm = { path = "../../svm", version = "=2.0.0" }
lumos-transaction-status = { path = "../../transaction-status", version = "=2.0.0" }
lumos-validator = { path = "../../validator", version = "=2.0.0" }
lumos-zk-token-sdk = { path = "../../zk-token-sdk", version = "=2.0.0" }
lumos-rbpf = "=0.8.0"
static_assertions = "1.1.0"
thiserror = "1.0"

[package]
name = "lumos-sbf-programs"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos"
readme = "README.md"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
sbf_c = []
sbf_rust = []
dummy-for-ci-check = [
    "sbf_c",
    "sbf_rust",
]

[build-dependencies]
walkdir = "2"

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
elf = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
miow = { workspace = true }
net2 = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-accounts-db = { workspace = true }
lumos-bpf-loader-program = { workspace = true }
lumos-cli-output = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-runtime = { workspace = true, features = ["dev-context-only-utils"] }
lumos-sbf-rust-invoke = { workspace = true }
lumos-sbf-rust-realloc = { workspace = true, features = ["default"] }
lumos-sbf-rust-realloc-invoke = { workspace = true }
lumos-sdk = { workspace = true }
lumos-svm = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-rbpf = { workspace = true }

[dev-dependencies]
lumos-ledger = { workspace = true }
lumos-runtime = { workspace = true, features = ["dev-context-only-utils"] }
lumos-sdk = { workspace = true, features = ["dev-context-only-utils"] }

[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/alloc",
    "rust/alt_bn128",
    "rust/alt_bn128_compression",
    "rust/big_mod_exp",
    "rust/call_depth",
    "rust/caller_access",
    "rust/curve25519",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/external_spend",
    "rust/finalize",
    "rust/get_minimum_delegation",
    "rust/inner_instruction_alignment_check",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/log_data",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/poseidon",
    "rust/rand",
    "rust/realloc",
    "rust/realloc_invoke",
    "rust/remaining_compute_units",
    "rust/ro_account_modify",
    "rust/ro_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/sibling_inner_instruction",
    "rust/sibling_instruction",
    "rust/simulation",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[patch.crates-io]
# We include the following crates as our dependencies from crates.io:
#
#  * lpl-associated-token-account
#  * lpl-instruction-padding
#  * lpl-memo
#  * lpl-pod
#  * lpl-token
#  * lpl-token-2022
#  * lpl-token-metadata-interface
#
# They are included indirectly, for example, `account-decoder` depends on
#
#     lumos-sdk = { workspace = true }
#
# and that is specified as
#
#     lpl-token = "=3.5.0"
#
# in `../../Cargo.toml`.
#
# `lpl-token`, in turn, depends on `lumos-program`, which we explicitly specify
# above as a local path dependency:
#
#     lumos-program = { path = "../../sdk/program", version = "=1.16.0" }
#
# Unfortunately, Cargo will try to resolve the `lpl-token` `lumos-program`
# dependency only using what is available on crates.io.  Crates.io normally
# contains a previous version of these crates, and we end up with two versions
# of `lumos-program` and `lumos-zk-token-sdk` and all of their dependencies in
# our build tree.
#
# If you are developing downstream using non-crates-io lumos-program (local or
# forked repo, or from github rev, eg), duplicate the following patch statements
# in your Cargo.toml. If you still hit duplicate-type errors with the patch
# statements in place, run `cargo update -p lumos-program` and/or `cargo update
# -p lumos-zk-token-sdk` to remove extraneous versions from your Cargo.lock
# file.
#
# There is a similar override in `../../Cargo.toml`.  Please keep both comments
# and the overrides in sync.
lumos-program = { path = "../../sdk/program" }
lumos-zk-token-sdk = { path = "../../zk-token-sdk" }
