[package]
name = "lumos-sbf-programs"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lumos"
readme = "README.md"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[workspace.package]
version = "2.0.0"
description = "Lumos SBF test program written in Rust"
authors = ["Lumos Labs Maintainers <maintainers@lumoslabs.com>"]
repository = "https://github.com/lumos-labs/lumos"
homepage = "https://lumoslabs.com/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
array-bytes = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
byteorder = { workspace = true }
elf = { workspace = true }
getrandom = { workspace = true }
itertools = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
miow = { workspace = true }
net2 = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rustversion = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

static_assertions = { workspace = true }
thiserror = { workspace = true }


lumos-account-decoder = { workspace = true }
lumos-accounts-db =  { workspace = true }
lumos-bpf-loader-program = { workspace = true }
lumos-cli-output = { workspace =  true,  optional = true }
lumos-ledger = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-program = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-program-test = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sbf-rust-128bit-dep = { workspace = true }
lumos-sbf-rust-invoke = { workspace = true }
lumos-sbf-rust-invoked = { workspace = true, default-features = false }
lumos-sbf-rust-many-args-dep = { workspace = true }
lumos-sbf-rust-mem = { workspace = true }
lumos-sbf-rust-param-passing-dep = { workspace = true }
lumos-sbf-rust-realloc = { workspace = true, default-features = false }
lumos-sbf-rust-realloc-invoke = { workspace = true }
lumos-sdk = { workspace = true }
lumos-lvm = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-validator = { workspace = true }
lumos-zk-token-sdk = { workspace = true }
lumos-rbpf = { workspace = true }


[features]
sbf_c = []
sbf_rust = []
dummy-for-ci-check = [
    "sbf_c",
    "sbf_rust",
]

[build-dependencies]
walkdir = "2"

[dependencies]
bincode = { workspace = true }
byteorder = { workspace = true }
elf = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
miow = { workspace = true }
net2 = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-accounts-db = { workspace = true }
lumos-bpf-loader-program = { workspace = true }
lumos-cli-output = { workspace = true }
lumos-logger = { workspace = true }
lumos-measure = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sbf-rust-invoke = { workspace = true }
lumos-sbf-rust-realloc = { workspace = true, features = ["default"] }
lumos-sbf-rust-realloc-invoke = { workspace = true }
lumos-sdk = { workspace = true }
lumos-lvm = { workspace = true }
lumos-transaction-status = { workspace = true }
lumos-rbpf = { workspace = true }
lumos-program = { workspace = true }
lumos-zk-token-sdk = { workspace = true }

[dev-dependencies]
lumos-ledger = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }

[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/alloc",
    "rust/alt_bn128",
    "rust/alt_bn128_compression",
    "rust/big_mod_exp",
    "rust/call_depth",
    "rust/caller_access",
    "rust/curve25519",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/external_spend",
    "rust/finalize",
    "rust/get_minimum_delegation",
    "rust/inner_instruction_alignment_check",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/log_data",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/poseidon",
    "rust/rand",
    "rust/realloc",
    "rust/realloc_invoke",
    "rust/remaining_compute_units",
    "rust/ro_account_modify",
    "rust/ro_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/sibling_inner_instruction",
    "rust/sibling_instruction",
    "rust/simulation",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[features]
default = ["display"]
display = ["lumos-cli-output"]
