[package]
name = "lpl-token-group-interface"
version = "0.3.0"
description = "Lumos Program Library Token Group Interface"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.1"
lumos-program = "2.0.0"
lpl-discriminator = { version = "0.3.0" , path = "../../libraries/discriminator" }
lpl-pod = { version = "0.3.0" , path = "../../libraries/pod", features = ["borsh"] }
lpl-program-error = { version = "0.5.0" , path = "../../libraries/program-error" }

[dev-dependencies]
lpl-type-length-value = { version = "0.5.0", path = "../../libraries/type-length-value", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
