[package]
name = "lumos-lvm"
description = "Lumos LVM"
documentation = "https://docs.rs/lumos-lvm"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = { workspace = true }
log = { workspace = true }
percentage = { workspace = true }

lumos-bpf-loader-program = { workspace = true }
lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-loader-v4-program = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-system-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_lvm"

[dev-dependencies]
bincode = { workspace = true }

lumos-logger = { workspace = true }
lumos-sdk = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }


