[package]
name = "lpl-governance-chat"
version = "0.2.9"
description = "Lumos Program Library Governance Chat Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }

lumos-program = { workspace = true }
#lumos-program-test = { workspace = true }
lumos-sdk = { workspace = true }
lpl-token = { workspace = true }
lpl-governance = { workspace = true }
lpl-governance-tools = { workspace = true }
lpl-governance-addin-api = { workspace = true }
lpl-governance-test-sdk = { workspace = true }
lpl-governance-addin-mock = { workspace = true }


[dev-dependencies]
assert_matches = "1.5.0"
proptest = "1.5"

[lib]
crate-type = ["cdylib", "lib"]
