[package]
name = "lumos-program-test"
description = "Lumos Program Test Framework"


version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
test-case = { workspace = true }
thiserror = { workspace = true }

crossbeam-channel = { workspace = true }
rbpf = { workspace = true }
tokio = { workspace = true, features = ["full"] }

lumos-accounts-db = { workspace = true }
lumos-banks-client = { workspace = true }
lumos-banks-interface = { workspace = true }
lumos-banks-server = { workspace = true }
lumos-bpf-loader-program = { workspace = true }
lumos-logger = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-lvm = { workspace = true }
lumos-vote-program = { workspace = true }
lumos-stake-program = { workspace = true }
