[package]
name = "lumos-sdk"
description = "Lumos SDK"
documentation = "https://docs.rs/lumos-sdk"
readme = "README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bitflags = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
derivation-path = { workspace = true }
digest = { workspace = true }
generic-array = { workspace = true }
hmac = { workspace = true }
itertools =  { workspace = true }
lazy_static = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
memmap2 = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
pbkdf2 = { workspace = true }
qstring = { workspace = true }
qualifier_attr = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
static_assertions = { workspace = true }
tiny-bip39 = { workspace = true }

#rand0-7 = { package = "rand", version = "0.7", optional = true }
rustversion = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
siphasher = { workspace = true }
thiserror = { workspace = true }
uriparse = { workspace = true }
wasm-bindgen = { workspace = true }

lumos-bytemuck = { workspace = true }
lumos-curve25519-dalek = { workspace = true }
lumos-ed25519-dalek = { workspace = true }
lumos-ed25519-dalek-bip32 = { workspace = true }
lumos-rand = { workspace = true }

lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-logger = { workspace = true }
lumos-program = { workspace = true }
lumos-sdk-macro = { workspace = true }
lumos-sdk = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }




[build-dependencies]
rustc_version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
