[package]
name = "lumos-sdk"
description = "Lumos SDK"
documentation = "https://docs.rs/lumos-sdk"
readme = "README.md"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
homepage = "https://www.uuhb.com"
edition = { workspace = true }

[dependencies]
assert_matches = "1.5.0"
base64 = "0.22.0"
bincode = "1.3.3"
bitflags = "2.4.2"
borsh = { version = "1.5.1", features = ["unstable__schema"] }
bs58 = "0.4.0"
byteorder = "1.5.0"
chrono = "0.4.34"
derivation-path = "0.2.0"
digest = "0.10.7"
generic-array = "0.14.7"
hmac = "0.12.1"
itertools = "0.10.5"
lazy_static = "1.5.0"
libsecp256k1 = "0.6.0"
log = "0.4.21"
memmap2 = "0.5.10"
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
num_enum = "0.7.2"
pbkdf2 = "0.11.0"
qstring = "0.7.2"
qualifier_attr = "0.2.2"
anyhow = "1.0.80"
hex = "0.4.3"
static_assertions = "1.1.0"
tiny-bip39 = "0.8.2"
rustversion = "1.0.14"
serde = { version = "1.0.204", features = ["derive"] }
serde_bytes = "0.11.14"
serde_derive = "1.0.103"
serde_json = "1.0.114"
serde_with = "2.3.3"
sha2 = "0.10.8"
sha3 = "0.10.8"
siphasher = "0.3.11"
thiserror = "1.0.57"
uriparse = "0.6.4"
wasm-bindgen = "0.2"


curve25519-dalek = { path = "../../curve25519-dalek/curve25519-dalek", features = ["alloc", "precomputed-tables", "zeroize"] }
ed25519-dalek = { path = "../../curve25519-dalek/ed25519-dalek", features = ["fast", "std", "zeroize", "digest", "rand", "u64_backend", "rand_core"] }
ed25519-dalek-bip32 = { path = "../../curve25519-dalek/ed25519-dalek-bip32", features = ["std"] }

bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
rand = { git = "https://github.com/gaokanxu/rand0_8.git", branch = "main", package = "rand", version = "0.8.5"}
rand0_7 = { git = "https://github.com/gaokanxu/rand0_7.git", branch = "main", package = "rand", version = "0.7.3" }
rand_core = { git = "https://github.com/gaokanxu/rand0_8.git", branch = "main", package = "rand_core", version = "0.6.4" }

lumos-frozen-abi = { path = "../frozen-abi" }
lumos-frozen-abi-macro = { path = "../frozen-abi/macro" }
lumos-logger = { path = "../logger" }
lumos-program = { path = "program" }
lumos-sdk-macro = { path = "macro" }



[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.68"

[build-dependencies]
rustc_version = "0.4"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
