[package]
name = "lumos-rpc-client-nonce-utils"
description = "Lumos RPC Client Nonce Utilities"
documentation = "https://docs.rs/lumos-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace =  true }
thiserror = { workspace = true }

lumos-clap-utils = { workspace = true }
lumos-rpc-client = { workspace = true }
lumos-sdk = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
lumos-account-decoder = { workspace = true }
lumos-rpc-client-api = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
