[package]
name = "lpl-math"
version = "0.2.0"
description = "Lumos Program Library Math"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "1.5.1"
num-derive = "0.4"
num-traits = "0.2"
lumos-program = "2.0.0"
thiserror = "1.0"
uint = "0.9"

[dev-dependencies]
proptest = "1.5.0"
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"
libm = "0.2.8"

[lib]
crate-type = ["cdylib", "lib"]


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
