[package]
name = "lpl-record"
version = "0.2.0"
description = "Lumos Program Library Record Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
lumos-program = "2.0.0"
thiserror = "1.0"
lpl-pod = { version = "0.3.0", path = "../../libraries/pod" }

[dev-dependencies]
lumos-program-test = "2.0.0"
lumos-sdk = "2.0.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
