[package]
name = "lumos-send-transaction-service"
description = "Lumos send transaction service"
documentation = "https://docs.rs/lumos-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
lumos-client = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
lumos-tpu-client = { workspace = true }

[dev-dependencies]
lumos-logger = { workspace = true }
lumos-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
