[package]
name = "lumos-poh"
description = "Lumos PoH"
documentation = "https://docs.rs/lumos-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }

crossbeam-channel = { workspace = true }
lumos-entry = { workspace = true }
lumos-ledger = { workspace = true }
lumos-measure = { workspace = true }
lumos-metrics = { workspace = true }
lumos-runtime = { workspace = true }
lumos-sdk = { workspace = true }
rand = { workspace = true }
lumos-logger = { workspace = true }
lumos-perf = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
