[package]
name = "lumos-vote-program"
description = "Lumos Vote program"
documentation = "https://docs.rs/lumos-vote-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
lumos-frozen-abi = { workspace = true }
lumos-frozen-abi-macro = { workspace = true }
lumos-metrics = { workspace = true }
lumos-program = { workspace = true }
lumos-program-runtime = { workspace = true }
lumos-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
lumos-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lumos_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
