[package]
name = "lumos-metrics"
description = "Lumos Metrics"
documentation = "https://docs.rs/lumos-metrics"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
gethostname = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
thiserror = { workspace = true }
env_logger = { workspace = true }
serial_test = { workspace = true }

lumos-crossbeam-channel = { workspace = true }
lumos-rand = { workspace = true }

lumos-sdk = { workspace = true }


[lib]
name = "lumos_metrics"

[[bench]]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
